### ISSUE TITLE
ERROR：The host must have IPv4. 

### ISSUE THREAD

**Issue by zhiao6** [spiritLHLS/peer2profit-one-click-command-installation#2]

**Comment by spiritLHLS** [comment]
尝试 curl ip.sb 看看是否回传地址，如果没有明晚我会进行修复使用多重判断

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/peer2profit-one-click-command-installation/commit/baaa4e7b7959612c91c8600757462bf016b09fb0

更新换了个站点判断，希望没问题吧
