### ISSUE TITLE
Error on arm64

### ISSUE THREAD

**Issue by mregha** [spiritLHLS/peer2profit-one-click-command-installation#4]
dpkg: error processing archive p2pclient_0.60_i386.deb (--install):
 package architecture (i386) does not match system (arm64)
Errors were encountered while processing:
 p2pclient_0.60_i386.deb
dpkg: error processing archive p2pclient_0.60_amd64.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 p2pclient_0.60_amd64.deb
 
Finish

**Comment by spiritLHLS** [comment]
Currently, it is officially shut down due to too many people abusing installers other than amd64/i386.
Previously, docker was used to solve problems with the ARM architecture, which is no longer valid and docker installations are no longer officially supported.
