### ISSUE TITLE
这个网站是不是跑路了？

### ISSUE THREAD

**Issue by StudenGit** [spiritLHLS/peer2profit-one-click-command-installation#5]
官网 https://peer2profit.io/ 已经打不开了

**Comment by spiritLHLS** [comment]
已失联起码1周，邮件询问暂未回复

**Comment by spiritLHLS** [comment]
询问了客服，只有电报的bot了：
[https://t.me/peer2profit_app_bot](https://t.me/peer2profit_app_bot?start=164225539661e2d42426a2f)
没有网站能用的了
